name: Deploy to telegram

on:
  workflow_dispatch: #allow jobs manual run
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://circleci/android:api-29-node
      - name: instalasi modules
        run: yarn

      - name: unit testing
        run: yarn test
