name: CI Prosses

on:
  workflow_dispatch: # allow jobs manual run
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: unit testing
        run: yarn test

  check-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: cleaning codes
        run: yarn lint
